using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;

namespace WasmBridge.Sdk;

/// <summary>
/// Scans already-built assemblies for types annotated with
/// <c>WasmBridge.Attributes.WasmBridgeTsInterfaceAttribute</c> and generates a single
/// partial <c>System.Text.Json.Serialization.JsonSerializerContext</c> registering each
/// root type - and a <c>List&lt;T&gt;</c> of it, a common bridge-method return shape - for
/// source-generated JSON serialization.
/// </summary>
/// <remarks>
/// Only covers the root types themselves (plus <c>List&lt;T&gt;</c> of each). Any other
/// shape actually passed to <c>JsonSerializer.Serialize</c>/<c>Deserialize</c> (e.g. a
/// <c>Dictionary&lt;string, T&gt;</c> wrapper) still needs its own hand-written
/// <c>[JsonSerializable]</c> entry in a separate context - this task has no visibility into
/// call sites, only into which types are marked as TypeScript-generation roots.
/// </remarks>
public sealed class GenerateJsonSerializerContextTask : Microsoft.Build.Utilities.Task
{
    private const string TsInterfaceAttributeFullName = "WasmBridge.Attributes.WasmBridgeTsInterfaceAttribute";
    private const string BridgeAttributesAssemblyName = "WasmBridge.Attributes";

    /// <summary>The resolved reference assemblies of the consuming project (e.g. <c>@(ReferencePath)</c>).</summary>
    [Required]
    public ITaskItem[] Assemblies { get; set; } = Array.Empty<ITaskItem>();

    /// <summary>Directory the generated context file is written to.</summary>
    [Required]
    public string OutputPath { get; set; } = string.Empty;

    /// <summary>The generated context file, if any root types were found.</summary>
    [Output]
    public ITaskItem[] GeneratedFiles { get; set; } = Array.Empty<ITaskItem>();

    public override bool Execute()
    {
        List<string> assemblyPaths = Assemblies
            .Select(item => item.ItemSpec)
            .Where(File.Exists)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        Directory.CreateDirectory(OutputPath);

        using var context = new MetadataLoadContext(new PathAssemblyResolver(assemblyPaths));

        var roots = new List<Type>();

        foreach (string path in assemblyPaths)
        {
            Assembly assembly;
            try
            {
                assembly = context.LoadFromAssemblyPath(path);
            }
            catch (Exception ex)
            {
                Log.LogMessage(MessageImportance.Low, $"GenerateJsonSerializerContext: skipping '{path}' ({ex.Message})");
                continue;
            }

            if (!ReferencesWasmBridgeAttributes(assembly))
            {
                continue;
            }

            foreach (Type type in GetLoadableTypes(assembly))
            {
                if (IsRoot(type))
                {
                    roots.Add(type);
                }
            }
        }

        if (roots.Count == 0)
        {
            GeneratedFiles = Array.Empty<ITaskItem>();
            return !Log.HasLoggedErrors;
        }

        string outputFile = Path.Combine(OutputPath, "WasmBridgeJsonContext.g.cs");
        File.WriteAllText(outputFile, GenerateFile(roots), Encoding.UTF8);

        GeneratedFiles = new ITaskItem[] { new TaskItem(outputFile) };
        return !Log.HasLoggedErrors;
    }

    private static string GenerateFile(List<Type> roots)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by WasmBridge.Sdk. Do not edit by hand.");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();

        foreach (Type root in roots.OrderBy(t => t.FullName, StringComparer.Ordinal))
        {
            string typeName = $"global::{root.FullName}";
            sb.AppendLine($"[JsonSerializable(typeof({typeName}))]");
            sb.AppendLine($"[JsonSerializable(typeof(List<{typeName}>))]");
        }

        sb.AppendLine("internal partial class WasmBridgeJsonContext : JsonSerializerContext");
        sb.AppendLine("{");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static bool IsRoot(Type type) =>
        type.GetCustomAttributesData().Any(a => a.AttributeType.FullName == TsInterfaceAttributeFullName);

    private static bool ReferencesWasmBridgeAttributes(Assembly assembly)
    {
        try
        {
            return assembly.GetReferencedAssemblies().Any(a => a.Name == BridgeAttributesAssemblyName);
        }
        catch
        {
            return false;
        }
    }

    private static IEnumerable<Type> GetLoadableTypes(Assembly assembly)
    {
        try
        {
            return assembly.GetTypes();
        }
        catch (ReflectionTypeLoadException ex)
        {
            return ex.Types.Where(t => t is not null)!;
        }
    }
}
