name: Publish WasmBridge.Net to NuGet

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore WasmBridge.Attributes/WasmBridge.Attributes.csproj

      - name: Pack
        run: dotnet pack WasmBridge.Attributes/WasmBridge.Attributes.csproj -c Release -o ./nupkg -p:PackageVersion=0.1.0

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ github.repository_owner }} # your nuget.org username (profile name), NOT your email address

      - name: Push to NuGet
        run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
